version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_auth_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ifortex
      POSTGRES_PASSWORD: ifortex
      POSTGRES_DB: auth_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_auth_db
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local